public class Calci {
    
    integer a = 20;
    integer b = 10;
    
    public void doSum(){
        
        integer res = a+b;
        System.debug('res ' + res);
    }
    public void doSub(){
        
        integer res = a-b;
        System.debug('res ' + res);
    }
    public void doMul(){
        
        integer res = a*b;
        System.debug('res ' + res);
    }
    public void doDiv(){
        
        integer res = a/b;
        System.debug('res ' + res);
    }
    

}